### ISSUE TITLE
Executing "create_statistics.sh"

### ISSUE THREAD

**Issue by inventorix** [rsennrich/ParZu#12]
Hello together, 

I have the Tüba-D/Z corpus in the right format ( CONLL, UTF-8 ).
When I run create_statistics.sh on the Tüba File CONLL2006 I get:
 "Illegal UTF-8 continuation" error.
If I run CONLL2011 there is another message saying:
'<meta-call>'/1: Undefined procedure: w/7
   Exception: (11) w(_4114, _4120, _4148, ne, _4152, _4126, _4132) ? 

Thanks for your help in advance.

**Comment by rsennrich** [comment]
can you confirm that the CONLL2006 is in UTF-8? If not, please confirm it to UTF-8 first. I don't have the latest release at hand, but there's a good chance that the original file is encoded in ISO 8859-1 (latin1). If so,  you can convert it like this on Linux:

iconv -f latin1 -t utf8 < infile > outfile

**Comment by inventorix** [comment]
in the Tüba-D/Z documentation CONLL2006 is clearly stated as UTF-8.
I tried iconv getting the same error message again.
Do you have an idea?

**Comment by rsennrich** [comment]
I got my hands on TüBa-D/Z Release 10.0, and updated create_statistics.sh to work with that format (tested with tuebadz-10.0-conll2010.txt ). Closing this issue.
