### ISSUE TITLE
Cannot parse file in docker

### ISSUE THREAD

**Issue by t-duan** [rsennrich/ParZu#14]
Hello Rico,
i have a naive question. How can I parse file in docker (windows 10)? I tried the following command line but it leads to error.
c:\user> docker run -i rsennrich/parzu python parzu.py -i tagged < sample_input
Then I got an error:

> In Zeile:1 Zeichen:54
>+ docker run rsennrich/parzu python parzu.py -i tagged < sample_input
>+                                                      ~
>Der Operator "<" ist für zukünftige Versionen reserviert.
>    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>    + FullyQualifiedErrorId : RedirectionNotSupported

Could you please tell me how to user it in the right way? Thanks a lot in advance!
Best, Tinghui

**Comment by rsennrich** [comment]
without having a windows machine to test, does "docker run -i" (for interactive) work?

docker run -i rsennrich/parzu -i tagged < sample_input

**Comment by rsennrich** [comment]
I hope you have been able to resolve this with other resources (looking at this again, it seems that '<' is not supported in your shell, not a ParZu-specific problem). If not, maybe using the new Docker container that provides a server is a good workaround.
