### ISSUE TITLE
ImportError: No module named pexpect when starting docker run

### ISSUE THREAD

**Issue by giovanni-annunzio** [rsennrich/ParZu#17]
Hi Rico,

I tried to run parzu from docker.

OS: Win10

Steps for reproducing:
-----------------------------------
$ **_docker pull rsennrich/parzu_**
OK

$ **_echo "Ich bin ein Berliner." | docker run -i rsennrich/parzu_**
Starting tokenizer
Starting POS-tagger
Starting preprocessor
**Traceback (most recent call last):**
  **File "/ParZu/external/clevertagger/clevertagger", line 14, in <module>**
    **import pexpect**
**ImportError: No module named pexpect**
Tokenizer v3
Language: de
reading transducer from file "/ParZu/external/zmorge-20150315-smor_newlemma.ca"...
finished.

Starting parser
Starting postprocessor

$ **_docker version_**
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Any idea how to fix it?`

Thank you in advance.

Regards
Giovanni

**Comment by giovanni-annunzio** [comment]
Hi Rico,

The error above is gone now, after pulling the latest build.

But if I try to start de webserver then I get the following error:
**_$ docker run -p 5003:5003 -i rsennrich/parzu_**
docker: Error response from daemon: driver failed programming external connectivity on endpoint compassionate_dewdney (038d379a620523114f8db5cbf40557f6e13d347ce5a68eb04fd646223ba98715): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5003:tcp:172.17.0.6:5003: input/output error.

I stopped and removed all containers, but the error is still thrown.

Do you have any ideas? I'm running on Win10.

Thx and regards
Giovanni

**Comment by rsennrich** [comment]
that sounds like a general Docker problem rather than a ParZu problem. Maybe this will help: https://stackoverflow.com/questions/44414130/docker-on-windows-10-driver-failed-programming-external-connectivity-on-endpoin

**Comment by giovanni-annunzio** [comment]
Ops, this was my fault, sorry.

After restarting the services (just a right click in the windows tray on the docker symbol and choose restart) the problem was fixed.
