### ISSUE TITLE
swi-prolog sfst

### ISSUE THREAD

**Issue by smukh93** [rsennrich/ParZu#21]
I cannot use sudo apt-get to download swi-prolog sfst. The other alternative is to clone the swi-prolog repo and build it. Does anyone have any other solution?

**Comment by rsennrich** [comment]
what system are you trying to install ParZu in?

Installing it as a Docker container should work on most modern operating systems.

If you're using a non-Debian Linux systems, and don't want to use Docker, there will probably be alternative packages to provide prolog; you're likely to have SFST from source.
