### ISSUE TITLE
Support --tokenized or --tokenized_lines in the REST API

### ISSUE THREAD

**Issue by johann-petrak** [rsennrich/ParZu#22]
It would be very cool if the server would support processing already tokenised text. For get, a parameter could indicate that the string is whitespace-separated tokens, and for POST requests with JSON, an array of tokens could get passed ass well. 

So ideally this would just be another REST parameter in addition to text and format, maybe "input" with possible values "tokenized"  and "tokenized_lines" and maybe also "plain", "preprocessed" and "tagged" to support everything the class actually supports.

**Comment by rsennrich** [comment]
most of these are now supported (except preprocessed). The parameter is "inputformat"

**Comment by johann-petrak** [comment]
Wow, great, thanks! 
Just out of curiosity, how fast will this make it into an updated docker image?

**Comment by rsennrich** [comment]
the docker image should automatically build, but I've now triggered the rebuild manually.
