### ISSUE TITLE
Cannot use the module

### ISSUE THREAD

**Issue by murro85** [rsennrich/ParZu#26]
Hi, i am really sorry if this issue is trivial, but I cannot seem to make this work. 

I extracted the module in my python37/Lib/site-package folder and tried to run the provided lines

import parzu_class as parzu #line1
options = parzu.process_arguments() #line2
ParZu = parzu.Parser(options) #line3
sentences = ParZu.main('Das ist ein Test. Das auch.') #line4
for sentence in sentences: #line5
    print sentence #line6

I had to change line 1 in "import parzu" because otherwise it would not find the module and line 6 which is missing the () for the print function.

I however still get the following error:

"module 'parzu' has no attribute 'process_arguments'"

Do you have any sugestion? 

I am using python on Windows 10, x64

**Comment by rsennrich** [comment]
Make sure there is no name clash with some other Python script, and that you're actually loading the right module. 

Even if you fix that, you might run into other problems: There's currently no support to run parzu natively in Windows, and I suggest you install and run it via Docker.
