### ISSUE TITLE
Online parser returns random sentences

### ISSUE THREAD

**Issue by fliegekunst** [rsennrich/ParZu#27]
Online demo version of ParZu (https://pub.cl.uzh.ch/demo/parzu/) returns a parse of a random sentence instead of the input. Is it a bug or a feature?

**Comment by rsennrich** [comment]
This seems to have fixed itself. Let me know if this occurs again, and I can have a closer look.

**Comment by rsennrich** [comment]
This seems ok so far - commit a38bca7ee76b90205a0cfca796b6ae537168f916 might have helped. Closing this.

**Comment by fliegekunst** [comment]
Entschuldigung, aber das Problem erschien wieder nachdem ich versucht habe,
einen größeren Textabschnitt mit ParZu zu bearbeiten. Dann startete ParZu
mir Random-Sätze aus meinem Text zu zeigen. Jetzt antwortet ParZu einfach
nicht mehr.
Es ist mir sehr schade, dass der Service nicht mehr läuft. Er war sehr
bequem für meinen Kurs der Korpuslinguistik, ich habe meinen Studenten
gezeigt, wie ein Parser eben für die deutsche Sprache arbeitet.
Mit Grüßen,
Lesia, Ukraine

Am So., 22. Sept. 2019 um 11:51 Uhr schrieb Rico Sennrich <
notifications@github.com>:

**Comment by rsennrich** [comment]
I updated the server to apply all updates to robustness in the face of timeouts (commit https://github.com/rsennrich/ParZu/commit/c2de8058c46459e2f684f3cffa8b755db50064ff ) and restarted it. Hope it will be more stable now.

**Comment by fliegekunst** [comment]
Thank you!

Rico Sennrich <notifications@github.com> schrieb am Do., 26. Sep. 2019,
18:10:

**Comment by rsennrich** [comment]
I found a problem with line breaks in the input that could cause the misalignment of input/output. This has been fixed in commit https://github.com/rsennrich/ParZu/commit/ed0e71c73a4df263f89253547fa6a7f8381fa045 - let me know if there are any more problems.
