### ISSUE TITLE
Error 502 with the demo of the ParZu

### ISSUE THREAD

**Issue by Lazarus971** [rsennrich/ParZu#30]
The page of the ParZu shows the Error 502. Is there any server problem or has the demo been closed? 
I need it for an study work at the University of Bonn. 
Best regards 
Lazarus971

**Comment by rsennrich** [comment]
thanks for reporting this; the demo is now up again.

(leaving this issue open, because I still need to fix the underlying issue with the server)

**Comment by IWummi** [comment]
The demo seems to be having a problem.
When trying to parse a sentence ("Das ist ein Test.") following message shows up:

> Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by rsennrich** [comment]
thanks, this is now working again. (underlying issue still unclear)

**Comment by rsennrich** [comment]
The demo is now running with a new server in the background which should be more stable. Closing this and hoping the issue doesn't come up again.
