### ISSUE TITLE
"Cannot open transducer file" unless a tagged file is supplied

### ISSUE THREAD

**Issue by tabidots** [rsennrich/ParZu#4]
Hello, I'm on Yosemite. I installed everything and downloaded the latest model files. When I run `./parzu` I get this error:

```
$ echo "Das ist ein Test." | ./parzu
Starting tokenizer
Starting POS-tagger
Starting preprocessor
* Load model
Tokenizer v3
Language: de

Error: Cannot open transducer file ../zmorge-20150315-smor_newlemma.ca

* Label sequences
* Done
reading transducer from file "external/zmorge-20150315-smor_newlemma.ca"...
finished.

Starting parser
Starting postprocessor
```

But if I use a tagged file, it works fine:

```
$ ./parzu -i tagged < external/clevertagger/sample_training_file.txt
Starting preprocessor
reading transducer from file "external/zmorge-20140521-smor_newlemma.ca"...
finished.

Starting parser
Starting postprocessor
1	Und	und	KON	KON	_	0	root	_	_ 
(usw...)
```

`/external/clevertagger/` contains `clevertagger` (folder), `hdt_ab.zmorge-20140521-smor_newlemma.model` and `zmorge-20150315-smor_newlemma.ca`.

in `clevertagger/config.py`, I have set `SMOR_MODEL = '../zmorge-20140521-smor_newlemma.ca'`.

in ParZu's `config.ini`, I have set `smor_model = external/zmorge-20150315-smor_newlemma.ca`.

Now, if you look at the error message above, you would think that it's the path in the clevertagger `config.py` causing the problem. But I can run `clevertagger` successfully on its own. So why can't ParZu seem to load `clevertagger`? Thanks for your help.

**Comment by rsennrich** [comment]
Hiya,

you set a relative path to SMOR_MODEL in clevertagger/config.py. This will be evaluated according to the current working directory, which is different depending on whether you call clevertagger directly, or call it through ParZu.

The script install.sh should set the correct (absolute) paths so that you can run ParZu and clevertagger.

best wishes,
Rico

**Comment by tabidots** [comment]
Ah, I found the culprit. `install.sh` contains some lines that don't work on OS X.

If I run `./install.sh`, I get this at the end:
```
sed: 1: "external/clevertagger/c ...": invalid command code e
sed: 1: "external/clevertagger/c ...": invalid command code e
sed: 1: "external/clevertagger/c ...": invalid command code e
sed: 1: "config.ini": command c expects \ followed by text
sed: 1: "config.ini": command c expects \ followed by text
```

Following [this answer](http://unix.stackexchange.com/a/92907/), I was able to get ParZu working by modifying `install.sh` like this:

```
# configure clevertagger
sed -e "s,^SMOR_MODEL =.*$,SMOR_MODEL = '$SCRIPTPATH/external/zmorge-20150315-smor_newlemma.ca'," "external/clevertagger/config.py" > "external/clevertagger/config_tmp.py"
sed -e "s,^CRF_MODEL =.*$,CRF_MODEL = '$SCRIPTPATH/external/hdt_ab.zmorge-20140521-smor_newlemma.model'," "external/clevertagger/config.py" > "external/clevertagger/config_tmp.py"
sed -e "s,^CRF_BACKEND_EXEC =.*$,CRF_BACKEND_EXEC = '$SCRIPTPATH/external/Wapiti/wapiti'," "external/clevertagger/config.py" > "external/clevertagger/config_tmp.py"
mv -- "external/clevertagger/config_tmp.py" "external/clevertagger/config.py"

# configure ParZu
sed -e "s,^smor_model =.*$,smor_model = $SCRIPTPATH/external/zmorge-20150315-smor_newlemma.ca," "config.ini" > "config_tmp.ini"
sed -e "s,^taggercmd =.*$,taggercmd = $SCRIPTPATH/external/clevertagger/clevertagger," "config.ini" > "config_tmp.ini"
mv -- "config_tmp.ini" "config.ini"
```

Thank you!
