### ISSUE TITLE
sfst library isn't available anymore

### ISSUE THREAD

**Issue by LilithWittmann** [rsennrich/ParZu#7]
I tried to setup ParZu but I didn't find the required sfst library anywhere (the ftp server seems to be down). Can you provide me a working download link or do you have any solution to work without this library?

**Comment by rsennrich** [comment]
which link did you try to follow? SFST is available as a Debian/Ubuntu package, or here: http://www.cis.uni-muenchen.de/~schmid/tools/SFST/

**Comment by LilithWittmann** [comment]
Thanks! I tried multiple links from the uni Stuttgart and none of them worked.
